### ISSUE TITLE
Delete the graph

### ISSUE THREAD

**Issue by jonnyjohnson1** [FalkorDB/falkordb-py#18] opened 2024-02-21 21:15 UTC
How can I delete the graph?

I've been playing around with adding information to it, and through the process I have created many duplicates. 

I hope for two things:
1. Remove duplicates
2. Delete the whole graph and start from scratch

I am going through the docs and can't seem to find it. Or... I found [this](https://docs.falkordb.com/commands/graph.delete.html), but don't understand how to actually execute it in my python. I just looked around the code base, hoping to find a function like g.select_graph but, in this case, it'd be something like g.delete_graph(<graph_name>), but that search was unsuccessful, too.

**Comment by swilly22** [comment] 2024-02-22 13:00
Using falkordb-py client:

```python
from falkordb import FalkorDB
db = FalkorDB(host='localhost', port=6379)
g = db.select_graph('MotoGP')
g.delete()
```

Will delete the entire graph.

To delete duplicates is a bit more complicated as we need to determine if two nodes / edges are duplicate of one another,
For example consider this query:
```cypher
MATCH (a:Person), (b:Person) WHERE a <> b AND a.name = b.name DELETE b
```
Here we made sure nodes `a` and `b` are different but they do have the same `name` attribute which we would like to keep unique, as such the query will delete the duplicate, in this case node `b`

**Closed** 2024-03-05 12:52 UTC
Labels: question
